README.md, src/FilePathsBase.jl, src/path.jl, test/path.jl
CC @vtjnash 
There are some open questions before we can merge this:
- I'm not happy with the names ``@__DIR_P__`` and ``@__FILE_P__``, does anyone have a better idea?
- What do we want to return if this is run from the REPL or ``julia -e``? Right now it always returns ``Path()``, but I'm not sure that is a good idea. Should we instead return ``nothing``?
=> Add @__DIR_P__, @__FILE_P__ and @LOCAL macro

.travis.yml, appveyor.yml, src/path.jl
It would be a good idea to enable nighties on Travis CI.
=> Test against Julia 1.0

src/FilePathsBase.jl
Calls to `checkbounds` that can happen in other scenarios will fail unless `ncodeunits` is defined.
=> Add ncodeunits

src/path.jl, src/posix.jl
=> Restrict all Path tuples to `Vararg{String}`

src/FilePathsBase.jl, src/path.jl, src/posix.jl, src/windows.jl, test/runtests.jl, test/testpaths.jl
The generally idea is that other packages should be able to register their custom path types with
FilePathsBase to hook into the `Path` and `p_str` interface.
Currently, libraries will need to run `FilePathsBase.register(MyPath)` in their `__init__()` function
and define an `ispathtype(::Type{MyType}, str)` method which checks to see if `str` matches their path syntax.
PosixPath and WindowsPath will still be the fallbacks for `Path` and `p_str`.
Use cases:
- `p"s3://mybucket/path/to/my/file.tar.gz"` -> S3Path
- `p"nfs://server/remote/system/file.jl"` -> NFSPath
- `p"\\hostname\sharename\path\to\my\file.txt"` -> UNCPath
Closes https://github.com/rofinn/FilePaths.jl/issues/30
=> Added a path types registry.

src/deprecates.jl, src/path.jl, test/path.jl
For now, as `join` on paths could be confused with string `join`, since a path is an `AbstractString`.
=> Undeprecate joinpath

appveyor.yml, src/FilePathsBase.jl, src/constants.jl, src/mode.jl, src/path.jl, src/posix.jl, src/windows.jl, test/mode.jl, test/path.jl, test/testpaths.jl
=> Drop string subtyping

.travis.yml, REQUIRE, appveyor.yml, src/FilePathsBase.jl, src/libc.jl, src/path.jl, src/posix.jl, src/status.jl, src/windows.jl, test/path.jl, test/runtests.jl
=> Add string and path concatenation operators

src/deprecates.jl
I didn't know this option existed, I should have done this months ago
=> Fix makepath deprecation to ignore existing directories (closes #26)

src/FilePathsBase.jl, src/deprecates.jl, src/libc.jl, src/path.jl, src/posix.jl, src/status.jl, src/system.jl, src/test.jl, src/windows.jl, test/runtests.jl, test/testpkg.jl
Use properties rather than accessors and add a factory method for `Path(path, segments)`.
=> Use properties rather than accessors

src/path.jl, src/test.jl
This seems to match what pathlib does now. Closes #19
=> Change parents to not error when no parents are found

src/path.jl, src/test.jl
Attempts to address https://github.com/oxinabox/DataDeps.jl/issues/100
=> Adds a fallback download method for when the destination is a string

src/FilePathsBase.jl, src/path.jl, src/test.jl, test/buffer.jl
Primary behaviour changes:
1. `parents(cwd())` includes the root if applicable (e.g., it isn't empty).
2. hasparent(p"/foo") returns true because the root is the parent.
NOTE: This aligns with pathlib to support @oxinabox's desire for `parent(fp) === fp` when there are no parents. I think I'd prefer the `rust` approach of returning `nothing`, but that would differ from the `Base.parent` behaviour for arrays.
=> Cleanup parent behaviour to include root path when applicable

src/test.jl
Test that `cp` and `sync` will error when the destination parent doesn't exist.
Related to https://github.com/JuliaCloud/AWSS3.jl/issues/76
=> `cp` consistency tests when destination parent doesn't exist

src/path.jl, src/test.jl, test/runtests.jl, test/system.jl
Closes #70 
NOTE: I'm running with the assumption that indexing and iteration should just cover the segments and not include the `anchor` (e.g., `/`, `c:\\`, `s3://mybucket/`)?
=> Add indexing and iteration support to the AbstractPath type

src/FilePathsBase.jl, src/path.jl, src/posix.jl, src/test.jl, src/windows.jl, test/runtests.jl, test/system.jl, test/testpkg.jl
=> Replace `ispathtype` and string constructor with `tryparse`

src/libc.jl
Closes https://github.com/rofinn/FilePaths.jl/issues/49
**Previous**
```julia
julia> using FilePathsBase
[ Info: Precompiling FilePathsBase [48062228-2e41-5def-b9a4-89aafe57970f]
julia> FilePathsBase.User(UInt64(12345))
signal (11): Segmentation fault: 11
in expression starting at REPL[2]:1
unsafe_load at ./pointer.jl:105 [inlined]
unsafe_load at ./pointer.jl:105 [inlined]
User at /Users/rory/repos/FilePathsBase.jl/src/libc.jl:63 [inlined]
User at /Users/rory/repos/FilePathsBase.jl/src/libc.jl:86
unknown function (ip: 0x115a618f2)
jl_apply at /Users/julia/buildbot/worker/package_macos64/build/src/./julia.h:1692 [inlined]
do_call at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:369
eval_body at /Users/julia/buildbot/worker/package_macos64/build/src/interpreter.c:0 …
```
=> Add some C_NULL checks for our libc calls

Project.toml, src/FilePathsBase.jl, src/system.jl, test/runtests.jl, test/system.jl
For reference, this is because CSV.jl is moving towards using mmap by default. It should still fallback if mmap fails (e.g., remote filepaths where reading everything into memory will still work).
=> Add mmap support for SystemPath

Project.toml, src/path.jl, src/test.jl
So that `collect(walkpath(...))` doesn't return a `Vector{Any}`
It does assume that `readpath(::P)::P` but i think that is a safe enough assumption.
If a new filepath wants to break that later we can deal with that later?
=> Make walkpath return a typed collection

Project.toml, src/FilePathsBase.jl
This changes the `eltype` of the `PATH_TYPES` constant from `DataType` to `Type`.  The reason for this is that `DataType` prevents abstract types from being used, which is perhaps a problem for `abstract type`, but becomes a problem because parametric types cannot be used either.  In other words, this PR enables the use of parametric types as path types.
=> fix inappropriately restrictive typing of PATH_TYPES

Project.toml, src/libc.jl, test/system.jl
Trying to fix the following error:
```MethodError: no method matching FilePathsBase.Group(::UInt64)```
by relaxing UInt types in Group similarly to [here](https://github.com/rofinn/FilePathsBase.jl/commit/8cc644314fdd6db9fac8e0a3e169d3a4523bc4d6).  
Initial commit is attempting to recreate the error as it occurs only on 32-bit machines.
=> Relaxing UInt types in Group

docs/src/api.md, src/FilePathsBase.jl, src/path.jl, src/test.jl
This implements what's discussed in #136 .
I have added a test for the interface that simply ensures that it is consistent with the definition provided here.  Interestingly, I have found that it is surprisingly tricky to come up with consistent tests as the apparent size of directory nodes can vary even on the same system (at least on `ext4`).
=> implemented diskusage

Project.toml, src/buffer.jl, test/buffer.jl
Fixes: https://github.com/rofinn/FilePathsBase.jl/issues/146
=> Add isopen method 

Project.toml, src/path.jl, src/system.jl, test/testpkg.jl
Closes #110 
```julia
julia> using FilePathsBase
julia> readdir(cwd())
12-element Vector{String}:
".DS_Store"
".git"
".github"
".gitignore"
"LICENSE.md"
"Manifest.toml"
"Project.toml"
"README.md"
"docs"
"foo.txt"
"src"
"test"
julia> readdir(cwd(); join=true)
12-element Vector{String}:
"/Users/rory/repos/FilePathsBase.jl/.DS_Store"
"/Users/rory/repos/FilePathsBase.jl/.git"
"/Users/rory/repos/FilePathsBase.jl/.github"
"/Users/rory/repos/FilePathsBase.jl/.gitignore"
"/Users/rory/repos/FilePathsBase.jl/LICENSE.md"
"/Users/rory/repos/FilePathsBase.jl/Manifest.toml"
"/Users/rory/repos/FilePathsBase.jl/Project.toml"
"/Users/rory/repos/FilePathsBase.jl/README.md"
"/Users/rory/repos/FilePathsBase.jl/docs"
"/Users/rory/repos/FilePathsBase.jl/foo.txt"
"/Users/rory/repos/FilePathsBase.jl/src" …
```
=> Support join and sort kwargs to both readdir and readpath

src/libc.jl, test/system.jl
I don't know if we want to do much else to handle missing cpasswd lookups, but this seems like a relatively safe way to pass the error down the line. I'm not sure if we want to do something similar for the string lookups?
Closes #130
=> Only warn if gid or uid can't be found

Project.toml, src/buffer.jl, test/buffer.jl
This adds a method for `FileBuffer`s to `readavailable` that precisely matches the behavior for `IOBuffer`s. This definition permits downstream niceties such as `CSV.read(::S3Path, ...)`.
I've also bumped the patch version as a separate commit.
=> Add `readavailable(::FileBuffer)`

src/FilePathsBase.jl
Something has started causing errors loading the package, because `Base.join` gets resolved before `FilePathsBase.join` gets defined. This is probably a julia bug, but as a workaround, for now, move the aliases.jl file earlier to define `FilePathsBase.join` earlier in the package.
=> Move aliases.jl file earlier

src/posix.jl, test/system.jl
`expanduser(p"/")` failed because `p"/"` doesn't have any segments. This fixes that.
I'd add a test as well, but I'm not sure where in the suite to put it...
=> Correctly handle / in expanduser

src/path.jl, src/system.jl
fixes #182, ref https://github.com/rofinn/FilePathsBase.jl/pull/183#issuecomment-2628159592
=> avoid constructing `Status` where not necessary
